server {
    listen 80;
    server_name adminhub.example.com;

    server_tokens on;

    location /static/ {
        root /usr/share/nginx/html;
        autoindex on;
    }

    location / {
        proxy_pass http://web:3000;
    }
}
