-- Apply before starting an installation using ddl-auto=validate.
-- The payload is our versioned-by-code internal SCA model, never the raw OSV response.
CREATE TABLE IF NOT EXISTS review_sca_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL UNIQUE REFERENCES reviews(id) ON DELETE CASCADE,
    result_json TEXT NOT NULL
);
