apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminhub-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminhub-web
  template:
    metadata:
      labels:
        app: adminhub-web
    spec:
      containers:
        - name: adminhub-web
          image: nginx:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
