package com.securedeploy.rule.model;

public enum RuleCategory {
    SECRET_MANAGEMENT,
    AUTHENTICATION,
    AUTHORIZATION,
    DATABASE,
    CONFIGURATION,
    INPUT_VALIDATION,
    FRONTEND_SECURITY,
    CLIENT_SECRET_EXPOSURE,
    CLIENT_STORAGE,
    CLIENT_XSS,
    CLIENT_REDIRECT,
    DEPENDENCY,
    DEVOPS_SECURITY,
    CONTAINER_SECURITY,
    CI_CD_SECURITY,
    KUBERNETES_SECURITY
}
